name: Bug
description: Reportar um bug ou comportamento equivocado
labels: ['bug']
body:
  - type: textarea
    attributes:
      label: Descrição do bug
      description: Descreva o que ocorreu de forma equivocada.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reprodução
      description: Descreva detalhamente como reproduzir o bug.
    validations:
      required: true